spring:
  cloud:
    gateway:
      routes:
        - id: test_route
          uri: https://www.baidu.com
          predicates:
            - Query=url,baidu

        - id: qq_route
          uri: https://qq.com
          predicates:
            - Query=url,qq


        - id: product_route
          uri: lb://smmall-product
          predicates:
            - Path=/api/product/**
          filters:
            - RewritePath=/api/(?<segment>/?.*), /$\{segment}

          #         这里由于优先级问题，会被路由到Admin_route,需要设置优先级，
          #          将精确路由放在高优先级，模糊路由放在低优先级
          #          这里配置的网关是配置服务product请求

        - id: admin_route
          uri: lb://renren-fast
#          lb表示的是负载均衡，后接的是Nacos中注册的微服务ID
          predicates:
            - Path=/api/**
          filters:
            - RewritePath=/api/(?<segment>/?.*), /renren-fast/$\{segment}



#前端项目：/api
#http://localhost:88/api/captcha.jpg     http://localhost:8080/renren-fast/captcha.jpg
#http://localhost:88/api/product/pmscategory/list/tree  http://localhost://10000/api/product/pmscategory/list/tree