spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://192.168.43.99:3306/SMmall-oms
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  application:
    name: smmall-order
  redis:
    host: smmall.com
    port: 6379
    password: 123456
    thymeleaf:
      cache: false
    session:
      store-type: redis
  rabbitmq:
    host: 192.168.43.99
    virtual-host: /
    publisher-confirm-type: correlated
    # publisher-confirms: true
    publisher-returns: true
    template:
     mandatory: true
    listener:
      simple:
       acknowledge-mode: manual
       #启动手动ACK机制，
mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
#这里通过配置文件进行主键自增
server:
  port: 9000
