server:
  port: 33333
spring:
  application:
    name: smmall-cart
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  redis:
    password: 123456
    port: 6379
    host: smmall.com
